name: conectar_ambiental
description: "Consultoria, consultoria ambiental, treinamento, curso, recuperação vegetal, recuperação florestal, recuperação de áreas degradadas, diagnósticos, laudos ambientais, licenciamento, consultoria ambiental na baixada santista, consultoria ambiental no estado de sao paulo, meliponicultura, meliponicultor, resgate de abelhas nativas, resgate de animais, manejo de animais, educação ambiental
  Conectar Ambiental - Consultoria Ambiental Especializada | Bertioga e Região
  Somos uma renomada consultoria ambiental em Bertioga, atendendo toda a região com soluções abrangentes. Oferecemos serviços de consultoria ambiental, treinamentos, cursos e diagnósticos, com foco em recuperação vegetal, recuperação de áreas degradadas e laudos ambientais. Nossa equipe de consultores altamente qualificados está comprometida em fornecer soluções personalizadas e eficazes para atender às necessidades ambientais de nossos clientes.
  Com vasta experiência em licenciamento ambiental e expertise em consultoria ambiental, ajudamos empresas e empreendimentos a alcançar a conformidade com as regulamentações ambientais e adotar práticas sustentáveis. Nosso compromisso com a preservação do meio ambiente se estende à região de Bertioga, contribuindo para a conservação da rica biodiversidade local.
  Além disso, oferecemos serviços especializados em birding observatory, manejo de animais e projetos de educação ambiental. Nosso objetivo é promover a conscientização e ações positivas em relação ao meio ambiente, visando um futuro mais sustentável.
  Conte com a Conectar Ambiental para obter soluções confiáveis e eficientes em consultoria ambiental em Bertioga e região. Entre em contato conosco para saber mais e iniciar uma parceria para preservar e valorizar nosso ambiente."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_social_button: ^1.1.4+1
  flutter_form_builder: ^9.2.1
  animations: ^2.0.0



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/LOGO_TRILHA_FUNDO TRANSPARENTE_COM TUCANO.png
    - assets/logo-conectar-ambiental.png
    - assets/tucano.png
    - assets/esquilo.png
    - assets/pica-pau.png
    - assets/equipe.png
    - assets/birdwatching.png

  fonts:
    - family: Pacifico
      fonts:
        - asset: assets/fonts/Pacifico-Regular.ttf
